@GJGWeb_HostAddress = https://localhost:7200

GET {{GJGWeb_HostAddress}}/api/escuderia

###

POST {{GJGWeb_HostAddress}}/api/escuderia
Content-Type: : application/json

{
    "Escuderia":
    {
        "Id: 12",
        "Nombre": "Gucci"
    }
}